# Generated by Django 3.1.3 on 2021-02-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome ')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('birth_day', models.DateField(verbose_name='birthDay')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('cpf', models.CharField(max_length=20, verbose_name='cpf')),
                ('start_date', models.DateField(verbose_name='StartDate')),
                ('team', models.IntegerField(choices=[(1, 'Mobile'), (2, 'FrontEnd'), (3, 'BackEnd')], default=None, verbose_name='status')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
