# Generated by Django 3.1.3 on 2021-02-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(1, 'WOMAN'), (2, 'MAN'), (3, 'OTHER')], default=None, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'FrontEnd'), (3, 'BackEnd')], default=None, verbose_name='team'),
        ),
    ]
